# Generated by Django 2.2.4 on 2019-08-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='名前')),
                ('memo', models.TextField(max_length=500, verbose_name='メモ')),
                ('d1s', models.IntegerField(blank=True, verbose_name='出勤時間1')),
                ('d1e', models.IntegerField(blank=True, verbose_name='退勤時間1')),
                ('d2s', models.IntegerField(blank=True, verbose_name='出勤時間2')),
                ('d2e', models.IntegerField(blank=True, verbose_name='退勤時間2')),
                ('d3s', models.IntegerField(blank=True, verbose_name='出勤時間3')),
                ('d3e', models.IntegerField(blank=True, verbose_name='退勤時間3')),
                ('d4s', models.IntegerField(blank=True, verbose_name='出勤時間4')),
                ('d4e', models.IntegerField(blank=True, verbose_name='退勤時間4')),
                ('d5s', models.IntegerField(blank=True, verbose_name='出勤時間5')),
                ('d5e', models.IntegerField(blank=True, verbose_name='退勤時間5')),
                ('d6s', models.IntegerField(blank=True, verbose_name='出勤時間6')),
                ('d6e', models.IntegerField(blank=True, verbose_name='退勤時間6')),
                ('d7s', models.IntegerField(blank=True, verbose_name='出勤時間7')),
                ('d7e', models.IntegerField(blank=True, verbose_name='退勤時間7')),
                ('d8s', models.IntegerField(blank=True, verbose_name='出勤時間8')),
                ('d8e', models.IntegerField(blank=True, verbose_name='退勤時間8')),
                ('d9s', models.IntegerField(blank=True, verbose_name='出勤時間9')),
                ('d9e', models.IntegerField(blank=True, verbose_name='退勤時間9')),
                ('d10s', models.IntegerField(blank=True, verbose_name='出勤時間10')),
                ('d10e', models.IntegerField(blank=True, verbose_name='退勤時間10')),
                ('d11s', models.IntegerField(blank=True, verbose_name='出勤時間11')),
                ('d11e', models.IntegerField(blank=True, verbose_name='退勤時間11')),
                ('d12s', models.IntegerField(blank=True, verbose_name='出勤時間12')),
                ('d12e', models.IntegerField(blank=True, verbose_name='退勤時間12')),
                ('d13s', models.IntegerField(blank=True, verbose_name='出勤時間13')),
                ('d13e', models.IntegerField(blank=True, verbose_name='退勤時間13')),
                ('d14s', models.IntegerField(blank=True, verbose_name='出勤時間14')),
                ('d14e', models.IntegerField(blank=True, verbose_name='退勤時間14')),
                ('d15s', models.IntegerField(blank=True, verbose_name='出勤時間15')),
                ('d15e', models.IntegerField(blank=True, verbose_name='退勤時間15')),
                ('d16s', models.IntegerField(blank=True, verbose_name='出勤時間16')),
                ('d16e', models.IntegerField(blank=True, verbose_name='退勤時間16')),
            ],
            options={
                'db_table': 'submit',
            },
        ),
    ]
