# Generated by Django 2.2.4 on 2019-08-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20190820_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='d10e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間10'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d10s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間10'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d11e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間11'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d11s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間11'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d12e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間12'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d12s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間12'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d13e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間13'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d13s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間13'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d14e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間14'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d14s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間14'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d15e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間15'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d15s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間15'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d16e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間16'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d16s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間16'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d1e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間1'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d1s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間1'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d2e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間2'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d2s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間2'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d3e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間3'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d3s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間3'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d4e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間4'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d4s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間4'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d5e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間5'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d5s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間5'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d6e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間6'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d6s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間6'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d7e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間7'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d7s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間7'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d8e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間8'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d8s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間8'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d9e',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='退勤時間9'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='d9s',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出勤時間9'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='memo',
            field=models.CharField(max_length=500, verbose_name='メモ'),
        ),
    ]
