# Generated by Django 2.2.4 on 2019-08-20 12:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_auto_20190820_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='sort_id',
            field=models.IntegerField(default=builtins.id, unique=True, verbose_name='sort'),
        ),
    ]
